package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestClassifyPivotRolePathSignals covers the signals that need no file on disk.
// Each case is a precedence decision the classifier has to get right, not just a
// happy path: vendored test files are vendored first, and a _test.go file inside
// testdata/ is a fixture the toolchain never builds.
func TestClassifyPivotRolePathSignals(t *testing.T) {
	cases := []struct {
		path string
		want string
	}{
		{"internal/cli/pivot.go", roleProduction},
		{"internal/cli/pivot_test.go", roleTest},
		{"internal/sem/testdata/sample.go", roleTestFixture},
		{"internal/sem/fixtures/graph.json", roleTestFixture},
		{"internal/api/mocks/client.go", roleTestFixture},
		{"vendor/github.com/x/y/y.go", roleVendor},
		{"vendor/github.com/x/y/y_test.go", roleVendor},
		{"internal/sem/testdata/thing_test.go", roleTestFixture},
	}
	for _, testCase := range cases {
		// Empty repo root: path signals only, no disk access.
		if got := classifyPivotRole(testCase.path, ""); got != testCase.want {
			t.Errorf("classifyPivotRole(%q) = %q, want %q", testCase.path, got, testCase.want)
		}
	}
}

// TestClassifyPivotRoleGeneratedHeader is the one signal that cannot be read off a
// path. It has to come from the file the generator wrote, so it is worth proving
// rather than assuming — a silently broken probe would report generated code as
// production and invite someone to hand-edit a file that gets overwritten.
func TestClassifyPivotRoleGeneratedHeader(t *testing.T) {
	root := t.TempDir()
	write := func(name, content string) {
		full := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("gen/stringer.go", "// Code generated by stringer. DO NOT EDIT.\n\npackage gen\n")
	write("gen/protobuf.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage gen\n")
	write("gen/script.py", "# Code generated by tooling. DO NOT EDIT.\n")
	write("gen/handwritten.go", "package gen\n\n// Code generated is discussed here but not as a header.\n")
	write("gen/empty.go", "")

	for path, want := range map[string]string{
		"gen/stringer.go":    roleGenerated,
		"gen/protobuf.go":    roleGenerated,
		"gen/script.py":      roleGenerated,
		"gen/handwritten.go": roleProduction,
		"gen/empty.go":       roleProduction,
		// Listed in the snapshot, absent from the working tree: the last signal
		// could not be checked, so the honest answer is unknown, not production.
		"gen/deleted.go": roleUnknown,
	} {
		if got := classifyPivotRole(path, root); got != want {
			t.Errorf("classifyPivotRole(%q) = %q, want %q", path, got, want)
		}
	}
}

// TestCollapsePivotPackagesRanksByVolume is the noise fix itself: many files in one
// package must come back as one actionable line, ordered so the biggest blast is
// read first, and carrying a command that actually checks them.
func TestCollapsePivotPackagesRanksByVolume(t *testing.T) {
	files := []pivotFile{
		{Path: "internal/sem/a_test.go", Language: "go", Distance: 2},
		{Path: "internal/sem/b_test.go", Language: "go", Distance: 1},
		{Path: "internal/sem/c_test.go", Language: "go", Distance: 2},
		{Path: "internal/cli/d_test.go", Language: "go", Distance: 1},
		{Path: "docs/notes.md", Language: "markdown", Distance: 2},
	}
	groups := collapsePivotPackages(files)
	if len(groups) != 3 {
		t.Fatalf("want 3 packages, got %d: %+v", len(groups), groups)
	}
	if groups[0].Package != "internal/sem" || groups[0].Files != 3 {
		t.Errorf("largest package should sort first, got %+v", groups[0])
	}
	if groups[0].Command != "go test ./internal/sem" {
		t.Errorf("want a runnable command, got %q", groups[0].Command)
	}
	if groups[0].Nearest != 1 {
		t.Errorf("nearest distance in the group should be 1, got %d", groups[0].Nearest)
	}
	// A package with no Go in it must not be handed a Go command it cannot run.
	var docs pivotPackageGroup
	for _, group := range groups {
		if group.Package == "docs" {
			docs = group
		}
	}
	if strings.HasPrefix(docs.Command, "go test") {
		t.Errorf("non-Go package got a Go command: %q", docs.Command)
	}
}

// TestWritePivotTextGroupsAndCollapses is the end of the story the role pass was
// added for: the report leads with a ranked summary, spells out the production
// work file by file, and collapses the test files to one line per package instead
// of printing all of them.
func TestWritePivotTextGroupsAndCollapses(t *testing.T) {
	response := pivotResponse{
		Prohibited: []string{"os/exec"},
		Repo:       "/tmp/entire-graph",
		Commit:     "2ff84460aaaa",
		MaxDepth:   2,
		Invalidated: []pivotFile{
			{Path: "internal/gitutil/git.go", Verdict: verdictInvalidated, Role: roleProduction, Why: "uses os/exec directly",
				Evidence: []pivotEdge{{Relation: "IMPORTS", Target: "os/exec", Confidence: 0.8, Line: 12}}},
			{Path: "internal/sem/a_test.go", Verdict: verdictInvalidated, Role: roleTest, Language: "go", Why: "uses os/exec directly"},
			{Path: "internal/sem/b_test.go", Verdict: verdictInvalidated, Role: roleTest, Language: "go", Why: "uses os/exec directly"},
		},
		AtRisk: []pivotFile{
			{Path: "internal/cli/verify.go", Verdict: verdictAtRisk, Role: roleProduction, Distance: 1, Why: "calls internal/gitutil/git.go directly"},
			{Path: "internal/sem/c_test.go", Verdict: verdictAtRisk, Role: roleTest, Language: "go", Distance: 1},
			{Path: "internal/sem/d_test.go", Verdict: verdictAtRisk, Role: roleTest, Language: "go", Distance: 2},
			{Path: "internal/sem/e_test.go", Verdict: verdictAtRisk, Role: roleTest, Language: "go", Distance: 2},
		},
		Safe:   []pivotFile{{Path: "internal/cli/help.go", Verdict: verdictSafe, Role: roleProduction}},
		Counts: pivotCounts{Invalidated: 3, AtRisk: 4, Safe: 1, Total: 8},
	}

	var buffer bytes.Buffer
	writePivotText(&buffer, response)
	out := buffer.String()

	for _, want := range []string{
		"Required remediation:  3 direct violation(s) (1 production, 2 test across 1 package(s))",
		"Production follow-up:  1 at-risk production file(s)",
		"Test fallout:          3 file(s) across 1 package(s)",
		"Coverage gaps:         0 unreached",
		"internal/gitutil/git.go [PRODUCTION]",
		"internal/cli/verify.go [PRODUCTION] (distance 1)",
		"go test ./internal/sem",
		// Addressed relatively or not, the repository is named.
		"Repo entire-graph at 2ff84460",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("report missing %q\n---\n%s", want, out)
		}
	}
	// The collapse is only worth anything if the individual test files are gone.
	for _, unwanted := range []string{"c_test.go", "d_test.go", "e_test.go"} {
		if strings.Contains(out, unwanted) {
			t.Errorf("test fallout should be collapsed, but %q was listed\n---\n%s", unwanted, out)
		}
	}
}
